# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# testdd.py
# Created on: 2017-07-05 11:29:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy.sa import *
import os
import fnmatch

# 空间上的筛选
inputdir=r"F:\WHZ\Zze\NEW\aa1_10m\2017\\"
#outputdir="D:\\BIN_SHP_refine_2\\"
pattern = '*.shp'
filenames_all=fnmatch.filter(os.listdir(inputdir), pattern)
#filenames_all = filenames_all[0]
select_shp = r"F:\WHZ\Zze\NEW\MASK\BigIslands.shp"
#select_shp = r"F:\WHZ\Zze\NEW\MASK\world_countries_arcgis.shp"
#select_shp = r"F:\WHZ\Zze\NEW\MASK\SMALL_ISLANDS.shp"
#select_shp = r"F:\WHZ\Zze\NEW\MASK\VerySmallIslands.shp"
#select_shp = "E:\\NEW\\REFERENCE\\GLOBAL_PLATFORM.shp"
#select_shp = "E:\\NEW\\REFERENCE\\GLOBAL_OWT.shp"
#select_shp = "E:\\NEW\\REFERENCE\\GLOBAL_GF.shp"

for i,filename in enumerate(filenames_all):
    #first,convert to INT format
    in_features=os.path.join(inputdir,filename)
    #fieldList = arcpy.ListFields(in_features)
    #lens = len(fieldList)
    #if lens == 4 :

        #arcpy.AddField_management(in_features, "AREA", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
        #arcpy.CalculateField_management(in_features, "AREA", "!SHAPE.AREA!", "PYTHON_9.3")
        #arcpy.AddField_management(in_features, "Label", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
        #out_feature = os.path.join(outputdir,filename)
        # Process: Select Layer By Location
    layername="Layer"+filename[:-4]
    arcpy.MakeFeatureLayer_management(in_features, layername)
    arcpy.SelectLayerByLocation_management(layername, "WITHIN_A_DISTANCE", select_shp, "10 Meters", "NEW_SELECTION", "NOT_INVERT")
    arcpy.CalculateField_management(layername, "Label", "9999", "PYTHON_9.3", "")
    print str(i)+'       '+filename + " has been finished!"
    #arcpy.CopyFeatures_management(select_shp, out_feature)
