# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# testdd.py
# Created on: 2017-07-05 11:29:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy.sa import *
import os
import fnmatch

# 空间上的筛选
inputdir=r"F:\WHZ\Zze\NEW\aa1\2017\\"
outputdir=r"F:\WHZ\Zze\NEW\PLAT_1\2017\\"
pattern = '*.shp'
filenames_all=fnmatch.filter(os.listdir(inputdir), pattern)


for filename in filenames_all:
    #first,convert to INT format
    in_features=os.path.join(inputdir,filename)
    out_feature=os.path.join(outputdir,filename)
    isExist = os.path.exists(out_feature)
    if not isExist:
        #out_feature = os.path.join(outputdir,filename)
        # Process: Select Layer By Location
        layername="Layer"+filename[:-4]
        #arcpy.MakeFeatureLayer_management(in_features, layername)
        arcpy.MakeFeatureLayer_management(in_features, layername, "Label < 9999", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;ID IDVISIBLE NONE; GRIDCODE GRIDCODE VISIBLE NONE;  Label Label VISIBLE NONE")
        arcpy.CopyFeatures_management(layername, out_feature)
        print filename + " has been finished!"
    #
